# Generated by Django 5.0.7 on 2024-10-14 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('delivery_cost', models.IntegerField()),
                ('resale_value', models.IntegerField()),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.product_type')),
            ],
        ),
    ]
