# Generated by Django 5.0.7 on 2024-09-03 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 21, 31, 52, 311176, tzinfo=datetime.timezone.utc)),
        ),
    ]
