# Generated by Django 5.0.7 on 2024-09-03 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_deliveries_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 21, 35, 56, 47108, tzinfo=datetime.timezone.utc)),
        ),
    ]
