# Generated by Django 5.0.7 on 2024-09-03 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_alter_deliveries_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='date_ordered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
