# Generated by Django 5.0.7 on 2024-10-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_alter_deliveries_date_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='non_edibile',
            new_name='non_edible',
        ),
    ]

